import * as THREE from "three";
import { zipSync } from "fflate";
import { exportToSTL } from "./stl";

export type ExportItem = { name: string; mesh: THREE.Mesh };

function encodeText(str: string): Uint8Array {
  // Route through ArrayBuffer to ensure the Uint8Array is in the correct realm
  // (TextEncoder in jsdom returns a jsdom-realm Uint8Array, which fflate rejects).
  const encoded = new TextEncoder().encode(str);
  return new Uint8Array(encoded.buffer, encoded.byteOffset, encoded.byteLength);
}

export function buildZipExport(parts: ExportItem[], dowels: ExportItem[]): Uint8Array {
  const files: Record<string, Uint8Array> = {};
  for (const p of parts) {
    files[`parts/${p.name}`] = new Uint8Array(exportToSTL(p.mesh, "binary"));
  }
  for (const d of dowels) {
    files[`dowels/${d.name}`] = new Uint8Array(exportToSTL(d.mesh, "binary"));
  }
  files["README.txt"] = encodeText(
    "Generated by Pasak — https://pasak.3dlab.id\n\n" +
    `Parts: ${parts.length}\n` +
    `Dowel pieces: ${dowels.length}\n\n` +
    "Print parts in the orientation provided.\n" +
    "Dowels can be printed or substituted with wood/metal dowels of matching diameter.\n",
  );
  return zipSync(files);
}
